Лабораторная работа "numpy и линейная алгебра"

Чтобы наша программа работала нам нужно подключить пакет numpy. Делается это с помощью "import numpy as np"

Согласно нашей задаче размер нашей матрицы равна 4. Потому мы присвоим N число 4

Для генерации квадратичной матрицы из случайных чисел мы воспользуемся функцией np.random(), а чтобы функция выводила элементы в соответствии со стандартным нормальным распределением мы добавим .randn, вписав внутри скобок "N, N", таким образом мы получим матрицу размером 4x4

In [6]:
import numpy as np

N = 4
A = np.random.randn(N, N)

print(A)

[[ 0.96570187 -0.36885181  0.17218165  0.77247751]
 [-1.24065481 -1.69657258  0.26417515  0.06632735]
 [-0.16573491  0.95839049  1.6302539   1.00835414]
 [-0.12850582  1.31654418  0.58345699  0.07313949]]


Далее нам нужен вектор W. Согласно задачи вектор должен быть случайным, но длиной 4, тем не менее не указано насколько именно случайно. У нас 2 варианта:
1) Он также должен быть со стандартным нормальным распределением
2) Он должен быть с определёнными ограничениями
Для первого случая мы воспользуемся np.random.randn(N), тем временем как для второго np.random.randint(), в скобках которого мы запишем минимальное значение, например, 0, максимальное 10 и длину N. Для первого случая вектор мы назовём W1, а для второго W2

In [15]:
import numpy as np

N = 4
A = np.random.randn(N, N)
W1 = np.random.randn(N)
W2 = np.random.randint(0, 10, N)

print("Вектор со стандартным нормальным распределением:", W1)
print("Вектор с случайным значением:", W2)

Вектор со стандартным нормальным распределением: [ 0.36250404 -2.34063449  0.2758389  -1.02811682]
Вектор с случайным значением: [8 1 5 1]


Теперь нам нужно решить линейное уровнение Ax=W. Для этого мы используем np.linalg.solve() вписав в него A и W1, W2

In [18]:
import numpy as np

N = 4
A = np.random.randn(N, N)
W1 = np.random.randn(N)
W2 = np.random.randint(0, 10, N)

x1 = np.linalg.solve(A, W1)
x2 = np.linalg.solve(A, W2)

print("Линейное уравнение при случайном векторе со стандартным нормальным распределением =", x1)
print("Линейное уравение при случайном векторе = ", x2)

Линейное уравнение при случайном векторе со стандартным нормальным распределением = [-0.84767031 -2.77730377  0.04574615  1.35908357]
Линейное уравение при случайном векторе =  [6.94269624 9.47165866 4.16783859 9.32343614]


Последней нашей задачей является вычисление нормы разности вектора Ax-W. Для этого мы воспользуемся p.linalg.norm и впишем матричное умножение "A @ x" и вычтем W

В конечном итоге наш итоговый результат выглядит так. Мы всё ещё можем изменять границы случайности вектора, если потребуется

In [19]:
import numpy as np

N = 4
A = np.random.randn(N, N)
W1 = np.random.randn(N)
W2 = np.random.randint(0, 10, N)

x1 = np.linalg.solve(A, W1)
x2 = np.linalg.solve(A, W2)

Diff1 = np.linalg.norm(A @ x1 - W1)
Diff2 = np.linalg.norm(A @ x2 - W2)

print("Линейное уравнение при случайном векторе со стандартным нормальным распределением =", x1)
print("Норма разности вектора 'Ax - W' при случайном векторе со стандартным нормальным распределением =", Diff1)

print("Линейное уравение при случайном векторе = ", x2)
print("Норма разности вектора 'Ax - W' при случайном векторе =", Diff2)

Линейное уравнение при случайном векторе со стандартным нормальным распределением = [-4.18152396 -3.85994541 -1.80160244 -1.09164625]
Норма разности вектора 'Ax - W' при случайном векторе со стандартным нормальным распределением = 1.6439175459749098e-15
Линейное уравение при случайном векторе =  [ 3.04666533  5.38148719  1.79840024 -1.37438926]
Норма разности вектора 'Ax - W' при случайном векторе = 1.3732700395566711e-15
